### ISSUE TITLE
Example Start package.json missing dotenv

### ISSUE THREAD

**Issue by mineshmshah** [apollographql/fullstack-tutorial#149]
The example project is missing the `dotenv` package in the  `package.json`.
This contradicts the tutorial here which suggests it should already me installed.
https://www.apollographql.com/docs/tutorial/mutation-resolvers/

**Comment by joelespinozaro** [comment]
I'm trying to connect to Apollo Studio, but it seems to be because I don't have ` dotenv ` package.

**Comment by fspaniol** [comment]
Done in #147
