### ISSUE TITLE
V3 update

### ISSUE THREAD

**Issue by rumanbsl** [apollographql/fullstack-tutorial#156]
Now that apollo-client 3 is released, when might we expect the tutorial to be updated?

**Comment by web-tama** [comment]
I also would like to know that.

**Comment by web-tama** [comment]
Ah, it has shown in this article.
"in the coming weeks and months"
https://www.apollographql.com/blog/announcing-the-release-of-apollo-client-3-0/

**Comment by web-tama** [comment]
Or might use this regarding of the apollo client so far.
https://www.apollographql.com/docs/react/get-started/

**Comment by StephenBarlow** [comment]
As of late 2020, the full-stack tutorial is updated for AC3
