### ISSUE TITLE
Error: Missing link and cache properties during initialization

### ISSUE THREAD

**Issue by wojciech-bilicki-oke** [apollographql/fullstack-tutorial#36]
When going along with the tutorial end trying to run the client. I got this error. Is the version of `apollo-client` specified in the `package.json` correct?

**Comment by wojciech-bilicki-oke** [comment]
<img width="1205" alt="screenshot 2018-11-16 at 13 43 14" src="https://user-images.githubusercontent.com/23211643/48622066-df4c5f00-e9a5-11e8-963f-d90272019eb1.png">

**Comment by wojciech-bilicki-oke** [comment]
This can be fixed by 
`
import { ApolloClient } from 'apollo-client';
import {InMemoryCache} from 'apollo-cache-inmemory';
import {HttpLink} from 'apollo-link-http';
import gql from 'graphql-tag';

const cache = new InMemoryCache();
const link = new HttpLink({
  uri: 'https://server-nsx7cr1cp.now.sh'
})
const client = new ApolloClient({
  cache,
  link
})
`

and should be reflected in the tutorial.

**Comment by funkybunky** [comment]
I guess, it would make more sense to just use apollo-boost for the tutorial. Then, indeed, giving just the uri is enough.

**Comment by KeevanDance** [comment]
Yeah, just following the tutorial as is in the docs results in this error! Thanks for posting the solution on getting around this @wojciech-bilicki-oke

**Comment by smolinari** [comment]
I'm updating the docs. PR to come.

Scott
