### ISSUE TITLE
Fix failing snapshots in final

### ISSUE THREAD

**Issue by cheapsteak** [apollographql/fullstack-tutorial#49]
Snapshots in final are currently failing on master  

I couldn't find the resolver for Rocket

<details>

   Queries
    ✕ fetches list of launches (37ms)
    ✓ fetches single launch (24ms)
  Mutations
    ✓ returns login token (15ms)
    ✕ books trips (13ms)

  ● Queries › fetches list of launches

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "Queries fetches list of launches 1".

    - Snapshot
    + Received

    @@ -1,26 +1,10 @@
      Object {
    -   "data": Object {
    -     "launches": Object {
    -       "cursor": "1143239400",
    -       "hasMore": false,
    -       "launches": Array [
    -         Object {
    -           "id": "1",
    -           "isBooked": true,
    -           "mission": Object {
    -             "missionPatch": "https://images2.imgbox.com/40/e3/GypSkayF_o.png",
    -             "name": "FalconSat",
    -           },
    -           "rocket": Object {
    -             "fullName": "Falcon 1",
    -           },
    -         },
    -       ],
    -     },
    -   },
    -   "errors": undefined,
    +   "data": undefined,
    +   "errors": Array [
    +     [ValidationError: Cannot query field "fullName" on type "Rocket". Did you mean "name"?],
    +   ],
        "extensions": undefined,
        "http": Object {
          "headers": Headers {
            Symbol(map): Object {},
          },

      87 |     const {query} = createTestClient(server);
      88 |     const res = await query({query: GET_LAUNCHES});
    > 89 |     expect(res).toMatchSnapshot();
         |                 ^
      90 |   });
      91 |
      92 |   it('fetches single launch', async () => {

      at Object.toMatchSnapshot (src/__tests__/integration.js:89:17)

  ● Mutations › books trips

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "Mutations books trips 1".

    - Snapshot
    + Received

    @@ -1,9 +1,9 @@
      Object {
    -   "data": null,
    +   "data": undefined,
        "errors": Array [
    -     [GraphQLError: Cannot return null for non-nullable field TripUpdateResponse.failure.],
    +     [ValidationError: Cannot query field "failure" on type "TripUpdateResponse".],
        ],
        "extensions": undefined,
        "http": Object {
          "headers": Headers {
            Symbol(map): Object {},

      153 |       variables: {launchIds: ['1', '2']},
      154 |     });
    > 155 |     expect(res).toMatchSnapshot();
          |                 ^
      156 |   });
      157 | });
      158 |

      at Object.toMatchSnapshot (src/__tests__/integration.js:155:17)

 › 2 snapshots failed.
Snapshot Summary
 › 2 snapshots failed from 1 test suite. Inspect your code changes or run `npm test -- -u` to update them.

</details>

**Comment by mannyluvstacos** [comment]
Hello, @cheapsteak !
#51 Should address the failing snapshot issue.

I verified what is current on the tutorial and made updates to the `mutation` and `query` in the integration test file.

I then made updates to the snapshot as the integration tests were no longer failing and the prior snapshot had captured errors output.
