### ISSUE TITLE
client's action button text doesn't change after pressing "Remove from Cart"

### ISSUE THREAD

**Issue by yuwenhuang** [apollographql/fullstack-tutorial#59]
I run the client with my local server.

After pressing the button "Remove from Cart", the text of the button doesn't change back to "Add to cart".

In the beginning I thought the local resolver doesn't work. However, I tried to console.log the `cartItems` array and found the mutation works, the item has been removed from the array, and the result of `isInCart` also changed.

"Cancel this trip" and "Add to cart" work fine.

**Comment by mwindson** [comment]
Because `apollo-client@2.5.0-alpha.2` has a bug, see also in this [issue](https://github.com/apollographql/apollo-client/issues/4284).

**Comment by xiangweilee** [comment]
I'm hitting the same error

**Comment by danilobuerger** [comment]
Duplicate of https://github.com/apollographql/apollo-client/issues/4284
