### ISSUE TITLE
react-emotion has been replaced by @emotion/styled

### ISSUE THREAD

**Issue by tab00** [apollographql/fullstack-tutorial#92]
I can't run the client parts of the tutorial at all because an error message appears saying the above.

Update the code to use @emotion/styled or some other styling framework.

**Comment by tab00** [comment]
Is anyone there?

**Comment by JEStaubach** [comment]
PR #103 updates dependencies and updates react-emotion to @emotion if you want to try it out

**Comment by jpvajda** [comment]
Will be addressed in https://github.com/apollographql/odyssey/pull/544
